name: Bug Report
description: Report unexpected behavior during a meeting session here
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce this issue.
    validations:
      required: true
  - type: input
    id: amazon-chime-sdk-js-version
    attributes:
      label: Amazon Chime SDK for JavaScript Version
      description: What version of our Amazon Chime SDK for JavaScript are you running?
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - iOS Webview
        - Android Chrome
        - Samsung Internet
    validations:
      required: true
  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What is the browser version?
    validations:
      required: true
  - type: textarea
    id: meeting-attendee-ids
    attributes:
      label: Meeting and Attendee ID Information.
      description: Provide specific meeting and attendee ID if you have.
  - type: textarea
    id: logs
    attributes:
      label: Browser console logs.
      description: Check our [debugging](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#debugging) FAQ section to provide this required information. Please attach INFO-level logs with timestamps to the report from *before* the session started up until the point at which the unexpected behavior occurred. For multi-participant calls, attach a log file for each participant if possible.
      render: shell
    validations:
      required: true